### ISSUE TITLE
Using Sideffect Variables via python-joern 

### ISSUE THREAD

**Issue by er4z0r** [fabsx00/python-joern#6]
I am trying to adopt your Taint-Style Description example for sprintf but am lost in the mix of python, groovy and germlin. Here is what I try to do:

```python
funs = ['sprintf']
for f in funs:
	#find calls of bad function
	print "Calls to evil function %s:" % f
	calls = j.runGremlinQuery("getCallsTo('%s')" % f) 
	for c in calls:
				
		#params = j.runGremlinQuery("g.v(%d).callToArguments().filter{ it.childNum!='0' }.definitions().filter{it.type=='Parameter'}"%c._id)
		params = j.runGremlinQuery("g.v(%d).callToArguments().filter{ it.childNum!='0' }.sideEffect{ paramName = '.*' }.filter{ it.code.matches(paramName) }.unsanitized{ it.isCheck( paramName ) }.params( paramName )"%c._id)
		if set(params):
			print "call: %s " % c['code']
			print "\tCan be reached from function parameters:"
			for p in params:
				print "\t\t%s" % p

```
However when I execute this script I get:
```
Traceback (most recent call last):
  File "my_query.py", line 23, in <module>
    params = j.runGremlinQuery("g.v(%d).callToArguments().filter{ it.childNum!='0' }.sideEffect{ paramName = '.*' }.filter{ it.code.matches(paramName) }.unsanitized{ it.isCheck( paramName ) }.params( paramName )"%c._id)
  File "/usr/local/lib/python2.7/dist-packages/joern-0.1-py2.7.egg/joern/all.py", line 44, in runGremlinQuery
    return self.gremlin.execute(finalQuery)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/ext/gremlin/__init__.py", line 36, in execute
    response = self.resources["execute_script"].post({"script": script})
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 288, in post
    raise_from(self.error_class(message, **content), error)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/util.py", line 215, in raise_from
    raise exception
py2neo.error.BadInputException: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: paramName for class: Script26
```
So it seems like groovy tries to do a replacement here looking for paramName, which is obviously wrong.
How do I need to escape this so groovy stays out of my gremlin code?

**Comment by vlad902** [comment]
While trying to parse the expression, the db sees that it doesn't have a definition for paramName and aborts because it doesn't look inside of the sideEffects for new variables or lazy load. You need to just replace that last call to .params(paramName) with .transform { it.params(paramName) } since paramName will be defined in the closure context when it's run.

**Comment by fabsx00** [comment]
Oh, nice. A conversation about joern where I am not one of the participants ;) Btw, there is also a mailing list if you prefer e-mail:
https://listserv.gwdg.de/mailman/listinfo/joern-users

**Comment by pgh15** [comment]
Hi Fabian, or anyone else who can help. I'm also trying to understand both unsanitized and isCheck but am not very successful. I can't get the code in the OP to work and it seems to have changed since the 0.2.5 paper. unsantized appears to take two parameters, both closures I believe. Is someone able to give me some sample code that highlights either or both unsafe argument to strcpy here?

void foo(str, len) {char *foo = malloc(10); strcpy(foo, str, len);}

i.e. len isn't checked to be less than anything, and, for example, str isn't checked to be non-null.

ps. I did look at the joern-users mailing list but it doesn't seem to be used. Is there discussion going on elsewhere?

**Comment by fabsx00** [comment]
Hi,
yes, I made a change to unsanitized for 0.3 because it was incomplete. As in the previous version, it takes only a single argument, the closure "sanitizer". However, this closure now also receives the symbol that is currently being tracked as an argument (s) in addition to the current statement (it), and returns an empty list if no sanitization occurs, and a non-empty list if it does.

In consequence, 'unsanitized({  })' is now 'unsanitized({ it, s ->})' and the tests for 'unsanitized' have been updated accordingly: https://github.com/fabsx00/python-joern/blob/master/testing/tests/dataFlowTests.py

Checkout the following example:
void foo(char *str, int len) {char *foo = malloc(10); memcpy(foo, str, len);}
void bar(char *str, int len) {char *foo = malloc(10); if(len < MAX) return; memcpy(foo, str, len);}

The query:
getArguments("memcpy", "2").unsanitized{ it, s -> it._().filter{ it.code.contains("<") };  }.locations()
returns foo, but not bar.

Hope this helps!

**Comment by fabsx00** [comment]
Oh, and, of course, if you want to make sure the tracked symbol is actually checked, something like this is better:

getArguments("memcpy", "2").unsanitized{ it, s -> it._().isCheck(".*" + s +".*")  }.locations()

Best,
Fabian

**Comment by cottfa** [comment]
Hi Fabian,

Thanks a lot! Reading the groovy and gremlin code makes my eyes hurt.

If you don't mind me asking one more thing. How can I use Pattern.quote() to quote things that I want to check with codeContains()? I had this code:
getArguments('memcpy','2').sideEffect{a=it.code}.uses().in('USE').filter{it.in('USE').filter{it.type == 'Condition'}.toList() == []}.filter{it.codeContains('.*alloc.*'+a+'.*').toList() == []} and it fell over with:
Dangling meta character '*' near index 9
.*alloc.** DataSize.*
I somehow need to quote the regex so that it doesn't end up containing quote chars. I saw some examples using Pattern.quote() but I'm not sure what I need to include to be able to use that. Or perhaps there's something better?

Thanks,
Paul

**Comment by cottfa** [comment]
ps. I'm pgh15. Didn't realise I already had another account.

**Comment by cottfa** [comment]
Never mind, figure it out. This works:

import java.util.regex.Pattern;getArguments('memcpy', '2').unsanitized{ it, s -> it._().isCheck('.*'+Pattern.quote(s)+'.*')}.locations()
